# Generated by Django 3.1.2 on 2020-10-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('descricao', models.CharField(max_length=254)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
