# Generated by Django 3.1.2 on 2020-10-15 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201014_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image_url',
        ),
    ]
